### PR TITLE
GET inventory

### PR DESCRIPTION
**Pull request by chad-scanlon**
# Description
Fixes # (issue)
## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Change Status
- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback
# How Has This Been Tested?
- [ ] Test A
- [ ] Test B
# Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Review by sablemadison — CHANGES_REQUESTED** [review]
Looks great! But it looks like Landing.js has code commented out in lines 35-44 and there are a lot of console.logs. If I recall the pull request GP correctly, I think those things shouldn't be merged in to the main repo

**Comment by chad-scanlon** [comment]
Darn and I went through beforehand and deleted a bunch of them. I clearly missed some. I'll go through again and clean them up

**Review by sablemadison — APPROVED** [review]
Looks great to me

**Review by ElainaJourney — APPROVED** [review]
Looks fantastic

**Pull request merged**
